// Generated by CoffeeScript 1.7.1
(function() {
  var path, through;

  through = require("through");

  path = require("path");

  module.exports = function(collateFolderName) {
    var files, onEnd, onFile, reg;
    collateFolderName = collateFolderName || "assets";
    reg = new RegExp(".*\/"+collateFolderName+"\/");
    files = [];
    onFile = function(file) {
      //rename to output at destination folder
          //start all files from occurance of collateFolderName
      var cwd = process.cwd();
      var lpath = file.path.replace(reg, "");
      if (lpath == file.path) return;
      file.path = path.join(cwd, lpath)
      file.base = cwd;
      file.cwd = cwd;
      return files.push(file);
    };
    onEnd = function() {
      files.forEach((function(_this) {
        return function(file) {
          return _this.emit("data", file);
        };
      })(this));
      return this.emit("end");
    };
    return through(onFile, onEnd);
  };

}).call(this);
